# Generated by Django 4.2 on 2023-05-03 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_borrow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow',
            name='returned',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
