# Generated by Django 4.2 on 2023-05-03 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_borrow_returned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow',
            name='is_returned',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
