# Generated by Django 4.2 on 2023-05-03 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_alter_borrow_is_returned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow',
            name='is_returned',
            field=models.BooleanField(default=False),
        ),
    ]
